name: Echo Test Workflow

on: [push, pull_request, release, issues, fork, delete, create, watch, workflow_dispatch]

jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Test
      run: echo "test"
